### ISSUE TITLE
Update Giant Crop Ring's manifest.json

### ISSUE THREAD

**Issue by Pathoschild** [danvolchek/StardewMods#1]
Giant Crop Ring's `manifest.json` doesn't have an [update key](https://stardewvalleywiki.com/Modding:SMAPI_APIs#Update_checks) (so SMAPI won't notify players about updates), and doesn't list CustomElementHandler as a dependency (so players don't get a friendly error if they forget to install that). Here's my suggested `manifest.json` content. :)

```json
{
   "Name": "Giant Crop Ring",
   "Author": "Cat",
   "Version": "1.0.0",
   "Description": "Adds a ring which increases the chance of getting giant crops.",
   "UniqueID": "cat.giantcropring",
   "EntryDll": "GiantCropRing.dll",
   "MinimumApiVersion": "2.0",
   "UpdateKeys": ["Nexus:1182"],
   "Dependencies": [
     {
       "UniqueID": "Platonymous.CustomElementHandler"
     }
   ]
}

```

**Comment by danvolchek** [comment]
This has been fixed in ad0607d. Thanks for the issue, I think this mod was released before update keys and dependencies were added to SMAPI and I must have forgotten to add them! :)
