### ISSUE TITLE
Feature Request: Extend Content Pack support to include markerTiles

### ISSUE THREAD

**Issue by MouseyPounds** [danvolchek/StardewMods#10]
(Desert Obelisk mod) Currently the  tilesheet for the Desert warp end point (markerTiles.xnb) must be replaced in the mod assets folder to be changed. Having the content pack support extended to include overrides for it will make it easier to change those tiles out and have recolor options. Supporting PNG format for it would be helpful as well.

**Comment by danvolchek** [comment]
Since SDV now has desert obelisks in vanilla in 1.4, Desert Obelisk is deprecated. Closing since this request is no longer valid. :)
