### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by ghost** [danvolchek/StardewMods#11]
I suggest MIT but it's completely up to you.

**Comment by danvolchek** [comment]
Thanks for the suggestion! I've looked into licenses before, but never really found one I liked. I'll take another look.

**Comment by ghost** [comment]
What are you looking for in a license? I could suggest one that best fits your wishes. IANAL but under US Copyright law, not having a license is the same as having full copyright. Your users have no legal ability to do anything with the software, even if the source is publicly available on github.

Considering this is a free modification for a commercial game, a permissive license makes sense to foster community interaction. Including modification, redistribution, and usage for any purpose. Of course as the author of this project it's ultimately up to you.
