### ISSUE TITLE
Better Fruit Trees not working as intended?

### ISSUE THREAD

**Issue by InkDragon** [danvolchek/StardewMods#4]
can't plant saplings next to each other with only one space between them. Using SMAPI 2.7 on 1.3.28 and the version for beta 1.3. There is no error in SMAPI, in game is just the default message of "to close to another tree"

unless I am misunderstanding the way the mod is supposed to work

**Comment by danvolchek** [comment]
Sorry for the long wait - I've fixed this problem in version 1.2.5. Please re-download it!
