### ISSUE TITLE
Pong - Skipped mod

### ISSUE THREAD

**Issue by rikai** [danvolchek/StardewMods#9]
Pong no longer runs in recent versions of the game with the below error:

> [SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.
[SMAPI]       - Pong 1.0 because it's no longer compatible. Please check for a new version at https://mods.smapi.io

I am assuming #6 fixes this, but am unsure. If it does, uploading a new version to nexus should be all that's needed. :)

**Comment by danvolchek** [comment]
Hey, thanks for the report!

The single player version of Pong does work, but I've been holding back from releasing it until I get multi player working. It looks like that's not going to happen, so I'll disable the multiplayer portion and release it on Nexus soon.

**Comment by danvolchek** [comment]
I've fixed this and uploaded version 1.1.0 to Nexus without MP support. Sorry for the delay!
